### ISSUE TITLE
(Frontend) Implement public transit

### ISSUE THREAD

**Issue by itggot-adrian-almetunsmeds** [itggot-adrian-almetunsmeds/magic-mirror-backend#33]
Implement a public transit component. Perhaps looking something like this: 
[https://www.figma.com/file/satQlHo0zr3bQSsd8VWhmw/MagicMirror?node-id=0%3A1](https://www.figma.com/file/satQlHo0zr3bQSsd8VWhmw/MagicMirror?node-id=0%3A1)

**Comment by adr29truck** [comment]
Implemented in #36
